services:
  # Backend API service
  - type: web
    name: stockbot-api
    runtime: docker
    rootDir: backend
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://your-vercel-app-url.vercel.app
      - key: ENVIRONMENT
        value: production
